#' Generate download button for ae tables
#'
#' @param db ae data frame usually generated by tidy_ae_table2(). It should contain the following columns:
#'            (1) ae: the name of ae
#'            (2) ae_label: whether no filter, or filter with AESER, or filter with AEREL...
#'            (3) n_1: the number of unique ae subjects in the treatment arm
#'            (4) n_2: the number of unique ae subjects in the control arm
#'            (5) pct_1: the percentage of unique ae subjects in the treatment arm
#'            (6) pct_2: the percentage of unique ae subjects in the coltrol arm
#' @param ae_label_download a string vector, specifying the ae label to be download. 
#'                          For example, it can be "with serious adverse events", 
#'                          or c("with serious adverse events", "with drug-related adverse events")
#' @param source a string to specify the text of source in the downloaded ae summary tables 
#' @param footnote a string to specify the text of footnote in the downloaded ae summary tables
#' @return some download buttons
#' @export
#'
#' @examples 
#' \dontrun{
#' tbl <- data.frame(ae = c("headache", "pain", "fever", "running nose", 
#'                          "fever", "headache", "running nose"),
#'                   ae_label = c("All", "All", "All", "All", "AESER", "AEREL", "AEREL"),
#'                   n_1 = c(2, 3, 1, 5, 1, 1, 3),
#'                   n_2 = c(4, 5, 3, 7, 3, 3, 5),
#'                   N_1 = rep(20, 7),
#'                   N_2 = rep(20, 7),
#'                   stratum = rep("NULL", 7))
#' tbl <- tbl %>% dplyr::mutate(pct_1 = n_1/N_1, pct_2 = n_2/N_2)
#' 
#' treatment_order = c("MK9999" = "Xanomeline", "Placebo" = "Placebo")
#' 
#' db <- list(table = tbl, treatment_order = treatment_order)
#' download_ae(db, ae_label_download = c("AESER", "AEREL"))
#' }

download_ae_reports <- function(db, ae_label_download, 
                                source = NULL, footnote = NULL){
  
  # Set the default value for souce and fottnote
  if(is.null(source)){
    source <- "[Study XXX: adam-adae, adam-adsl]"
  }
  
  if(is.null(footnote)){
    # c("{^\\dagger}This is footnote 1", "This is footnote 2"), 
    footnote <- c("Every participant is counted a single time for each applicable specific adverse event.", 
                  "Non-serious adverse events up to 14 days of last dose and serious adverse events include all records with no upper limit.",
                  "Adverse event terms are from MedDRA Version 22.1.",
                  "Database Cutoff Date:")
  }
  
  # Create a temporary dic to store the rtf file
  temp_dir <- tempdir()
  
  # Round the percentage into 2 digits
  db$table$pct_1 <- paste0("(", round(db$table$pct_1, 2), ")")  
  db$table$pct_2 <- paste0("(", round(db$table$pct_2, 2), ")")  
  
  # Ensure the "All" ae_label is included
  ae_label_download <- unique(c(ae_label_download, "All"))
  
  for (ae_idx in seq_along(ae_label_download)) {
    
    ## Define the filer according to the interested AE
    temp_ae_label <- ae_label_download[ae_idx]
    
    db$table %>% 
      subset(ae_label == temp_ae_label) %>%
      select(c(ae, n_1, pct_1, n_2, pct_2)) %>%
      rtf_title(paste0("Analysis of Participants ", tools::toTitleCase(temp_ae_label), " All Participants as Treated")) %>%
      rtf_colheader( colheader = paste0('"| ', names(db$treatment_order)[1], " | ", names(db$treatment_order)[2], " "),
                     col_rel_width = c(4, rep(2, 2)) ) %>%
      rtf_colheader(" | n | (%) | n | (%) ",
                    col_rel_width = c(4, rep(1, 4)),
                    border_top = c("", rep("single", 4)),
                    border_left = c("single", rep(c("single", ""), 2)) ) %>%
      rtf_body(col_rel_width = c(4, rep(1, 4)),
               text_justification = c("l", rep("c", 4)),
               border_left = c("single", rep(c("single", ""), 2))) %>%
      rtf_footnote(footnote) %>%
      rtf_source(source) %>%
      rtf_encode() %>%
      write_rtf(paste0(temp_dir, "/ae_", gsub(" ", "_", temp_ae_label), ".rtf"))
  }
  
  download_file(
    path = list.files(path = temp_dir, full.names = TRUE),
    output_name = "AE Summary Count Tables",
    button_label = "Download All AE Summary Count Tables",
    button_type = "danger",
    has_icon = TRUE,
    icon = "fa fa-save",
    self_contained = FALSE
  )
  
  
}